CREATE TABLE tds_nous_usuario (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nm_usuario VARCHAR2(100) NOT NULL,
    ds_email VARCHAR2(150) NOT NULL,
    ds_senha VARCHAR2(120) NOT NULL,
    dt_nascimento DATE NOT NULL,
    ds_role VARCHAR2(30) DEFAULT 'ROLE_ALUNO' NOT NULL,
    CONSTRAINT pk_nous_usuario PRIMARY KEY (id_usuario),
    CONSTRAINT uq_nous_email UNIQUE (ds_email),
    CONSTRAINT ck_nous_usuario_role CHECK (ds_role IN ('ROLE_ALUNO', 'ROLE_EDUCADOR'))
);
