CREATE TABLE tds_nous_trilha (
    id_trilha NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ds_titulo VARCHAR2(120) NOT NULL,
    ds_descricao VARCHAR2(600) NOT NULL,
    ds_categoria VARCHAR2(60) NOT NULL,
    CONSTRAINT pk_nous_trilha PRIMARY KEY (id_trilha),
    CONSTRAINT ck_nous_trilha_cat CHECK (ds_categoria IN (
        'Saude Mental', 'Gestao Emocional', 'Foco nos Estudos', 'Comunicacao', 'Autoconfianca'
    ))
);

CREATE TABLE tds_nous_checkin_emocional (
    id_checkin NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_usuario NUMBER NOT NULL,
    dt_checkin DATE DEFAULT SYSDATE NOT NULL,
    nr_humor NUMBER(1) NOT NULL,
    ds_comentario VARCHAR2(300),
    CONSTRAINT pk_nous_checkin PRIMARY KEY (id_checkin),
    CONSTRAINT fk_nous_checkin_usuario FOREIGN KEY (id_usuario)
        REFERENCES tds_nous_usuario (id_usuario),
    CONSTRAINT ck_nous_humor CHECK (nr_humor BETWEEN 1 AND 5)
);

CREATE TABLE tds_nous_progresso_trilha (
    id_progresso NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_usuario NUMBER NOT NULL,
    id_trilha NUMBER NOT NULL,
    st_trilha VARCHAR2(20) NOT NULL,
    dt_inicio DATE NOT NULL,
    dt_conclusao DATE,
    CONSTRAINT pk_nous_progresso PRIMARY KEY (id_progresso),
    CONSTRAINT fk_nous_prog_usuario FOREIGN KEY (id_usuario)
        REFERENCES tds_nous_usuario (id_usuario),
    CONSTRAINT fk_nous_prog_trilha FOREIGN KEY (id_trilha)
        REFERENCES tds_nous_trilha (id_trilha),
    CONSTRAINT uq_nous_progresso_usuario_trilha UNIQUE (id_usuario, id_trilha),
    CONSTRAINT ck_nous_status CHECK (st_trilha IN ('Iniciada', 'Concluida')),
    CONSTRAINT ck_nous_datas CHECK (dt_conclusao IS NULL OR dt_conclusao >= dt_inicio)
);

CREATE INDEX ix_checkin_usuario ON tds_nous_checkin_emocional(id_usuario);
CREATE INDEX ix_prog_usuario ON tds_nous_progresso_trilha(id_usuario);
CREATE INDEX ix_prog_trilha ON tds_nous_progresso_trilha(id_trilha);
