CREATE TABLE tds_nous_auditoria_usuario (
    id_auditoria NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_usuario_ref NUMBER,
    operacao VARCHAR2(10),
    usuario_bd VARCHAR2(100),
    dt_operacao DATE,
    dados_old CLOB,
    dados_new CLOB,
    CONSTRAINT pk_auditoria PRIMARY KEY (id_auditoria)
);

CREATE OR REPLACE TRIGGER trg_auditoria_usuario
AFTER INSERT OR UPDATE OR DELETE ON tds_nous_usuario
FOR EACH ROW
DECLARE
    v_old CLOB;
    v_new CLOB;
BEGIN
    IF INSERTING THEN
        v_new :=
            '{' ||
            '"id_usuario":"' || :NEW.id_usuario || '",' ||
            '"nome":"' || :NEW.nm_usuario || '",' ||
            '"email":"' || :NEW.ds_email || '",' ||
            '"role":"' || :NEW.ds_role || '"' ||
            '}';

        INSERT INTO tds_nous_auditoria_usuario
        (id_usuario_ref, operacao, usuario_bd, dt_operacao, dados_old, dados_new)
        VALUES
        (:NEW.id_usuario, 'INSERT', USER, SYSDATE, NULL, v_new);

    ELSIF UPDATING THEN
        v_old :=
            '{' ||
            '"id_usuario":"' || :OLD.id_usuario || '",' ||
            '"nome":"' || :OLD.nm_usuario || '",' ||
            '"email":"' || :OLD.ds_email || '",' ||
            '"role":"' || :OLD.ds_role || '"' ||
            '}';

        v_new :=
            '{' ||
            '"id_usuario":"' || :NEW.id_usuario || '",' ||
            '"nome":"' || :NEW.nm_usuario || '",' ||
            '"email":"' || :NEW.ds_email || '",' ||
            '"role":"' || :NEW.ds_role || '"' ||
            '}';

        INSERT INTO tds_nous_auditoria_usuario
        (id_usuario_ref, operacao, usuario_bd, dt_operacao, dados_old, dados_new)
        VALUES
        (:NEW.id_usuario, 'UPDATE', USER, SYSDATE, v_old, v_new);

    ELSIF DELETING THEN
        v_old :=
            '{' ||
            '"id_usuario":"' || :OLD.id_usuario || '",' ||
            '"nome":"' || :OLD.nm_usuario || '",' ||
            '"email":"' || :OLD.ds_email || '",' ||
            '"role":"' || :OLD.ds_role || '"' ||
            '}';

        INSERT INTO tds_nous_auditoria_usuario
        (id_usuario_ref, operacao, usuario_bd, dt_operacao, dados_old, dados_new)
        VALUES
        (:OLD.id_usuario, 'DELETE', USER, SYSDATE, v_old, NULL);
    END IF;
END;
/
